openapi: 3.2.0
info:
  description: '# Introduction

    Welcome to the IntelyCare API documentation, your gateway to seamless integration with the IntelyCare Staffing platform. Our REST API empowers clients to efficiently create shift requests, enabling a streamlined process for managing workforce scheduling. By leveraging this API, you can enhance your systems with real-time information about shift status, including when a shift has been filled and details about the assigned IntelyPro.


    # Overview


    The IntelyCare API facilitates communication between your application and the IntelyCare platform, enabling a seamless exchange of data. This documentation serves as a comprehensive guide to help you integrate your systems with our powerful RESTful API. All requests and responses are JSON-encoded, and use standard HTTP response codes and authentication schemes. Bulk operations are not supported. You can work with only one object per request.


    To get started with the IntelyCare API, refer to the detailed documentation below. We provide comprehensive information on authentication, endpoints, request and response formats, and error handling.


    # Authentication


    IntelyCare offers the following authentication schemes:


    | Type                      | Usage       | Description                                                    | Example                                                                   |

    | ------------------------- | ----------- | -------------------------------------------------------------- | ------------------------------------------------------------------------- |

    | apiKey                    | REST APIs   | Required as `X-API-KEY` header for all RESTful calls           | `d1015a83-9f5f-4a4d-b5fd-4e756ed1d282`                                    |

    | HMAC Signature (SHA256)   | Webhooks    | Provided as `X-Signature-IC` header on all webhooks            | `bcc151a55acf3d93c097e768f2b96f82d91b56d6fe2a102818b70f0fdfd0ccd1`        |


    > :memo: **Note:** API Keys are tied to individual clients and cannot be used outside their provided scope


    # Support and Assistance


    If you have any questions, encounter issues, or require assistance during the integration process, our dedicated support team is here to help. Reach out to apisupport@intelycare.com for prompt and reliable assistance.


    Thank you for choosing IntelyCare. Let''s build a more efficient and connected healthcare workforce together!

    '
  version: 1.0.0
  title: IntelyCare API Documentation Shift API
  contact:
    name: API Support
    email: apisupport@intelycare.com
  x-logo:
    url: https://www.intelycare.com/wp-content/uploads/2023/08/ic-logo-2-1.svg
    altText: IntelyCare Logo
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: //api.intelycare.com/external-scheduling/v1/
  description: Default server
- url: //api.pre.prod01.platform.intelycare.com/external-scheduling/v1/
  description: Sandbox server
security:
- ApiKeyAuth: []
- HMACSignature: []
tags:
- name: Shift
  description: Integrate with the IntelyCare platform to create shift requests effortlessly. Our API allows you to programmatically submit and manage shift requests, providing you with the flexibility to adapt to your workforce scheduling needs.
paths:
  /api/shifts:
    post:
      tags:
      - Shift
      operationId: shift_create_api_v1
      summary: Create
      security:
      - ApiKeyAuth: []
      parameters:
      - name: X-API-KEY
        in: header
        description: API key issued to a specific client. This can only be used to access data within the client scope.
        example: d1015a839f5f
        required: true
        schema:
          type: string
      - name: X-CLIENT-ID
        in: header
        description: Intelycare's Unique identifier of the client.
        example: '1234'
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - externalShiftId
              - shiftStartTime
              - shiftEndTime
              - shiftUnit
              - healthcareProfessionalType
              - shiftSource
              properties:
                externalShiftId:
                  description: Unique identifier for the shift
                  type: string
                shiftStartTime:
                  description: Shift start date/time can be in the UTC timezone in ISO 8601 format ex. "2024-01-24T05:04:34Z" OR Local Time by omitting the "Z" at the end. ex. "2024-01-24T05:04:34". The local time will be based on the configuration of the facility in the IntelyCare system.
                  type: string
                  example: 'UTC: 2024-01-24T05:04:34Z, local time: 2024-01-24T05:04:34'
                shiftEndTime:
                  description: Shift end date/time can be in the UTC timezone in ISO 8601 format ex. "2024-01-24T05:04:34Z" OR Local Time by omitting the "Z" at the end. ex. "2024-01-24T05:04:34". The local time will be based on the configuration of the facility in the IntelyCare system.
                  type: string
                  example: 'UTC: 2024-01-24T05:04:34Z, local time: 2024-01-24T05:04:34'
                shiftUnit:
                  description: Facility unit where the care should be delivered by the healthcare professional
                  type: string
                healthcareProfessionalType:
                  description: 'Healthcare professional qualification needed for the given shift. For example: “CNA”,”LPN”,”RN”.'
                  type: string
                shiftSource:
                  description: Shift origination point
                  type: string
                timezone:
                  description: Timezone for the shifts
                  type: string
                shiftBoostPercentage:
                  description: Percentage amount for boosting the shift
                  type: integer
                  default: 0
            example:
              externalShiftId: '2546810'
              shiftStartTime: '2024-01-16T23:00:00'
              shiftEndTime: '2024-01-17T07:00:00'
              shiftUnit: 1st Floor
              healthcareProfessionalType: LPN
              shiftSource: qwerty
              shiftBoostPercentage: 10
              timezone: ET
            x-codeSamples:
            - lang: cURL
              label: CLI
              source: 'curl --request POST \

                --url ''https://data.apiexample.com/api/example/batch_query/json?format=json'' \

                --header ''content-type: application/octet-stream: '' \

                --data ''{}''

                '
      responses:
        '200':
          description: 200 OK
          content:
            application/json:
              example:
                data:
                  clientId: 1234
                  internalShiftId: 10174202
                  externalShiftId: '2546810'
                  shiftStartTime: '2024-01-16T23:00:00'
                  shiftEndTime: '2024-01-17T07:00:00'
                  shiftDate: '2024-01-16'
                  shiftUnit: 1st Floor
                  healthcareProfessionalType: LPN
                  shiftSource: qwerty
                  shiftBoostPercentage: 10
                  timezone: ET
        '400':
          description: 400 Bad Request
          headers:
            IC-CorrelationID:
              $ref: '#/components/schemas/IC-CorrelationID'
          content:
            application/json:
              examples:
                foo:
                  value:
                    message: Invalid input- Shift end time must be later than the shift start time.
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '422':
          description: 422 Unprocessable Entity
          headers:
            IC-CorrelationID:
              $ref: '#/components/schemas/IC-CorrelationID'
          content:
            application/json:
              examples:
                foo:
                  value:
                    message: Invalid input- shiftEndTime must be a date in the present or in the future.
  /api/shifts/{shiftId}:
    put:
      tags:
      - Shift
      operationId: shift_update_api_v1
      summary: Update
      security:
      - ApiKeyAuth: []
      parameters:
      - name: X-API-KEY
        in: header
        description: API key issued to a specific client. This can only be used to access data within the client scope.
        example: d1015a83-9f5f-4a4d-b5fd-4e756ed1d282
        required: true
        schema:
          type: string
      - name: X-CLIENT-ID
        in: header
        description: Intelycare's Unique identifier of the client.
        example: '1234'
        required: true
        schema:
          type: string
      - name: shiftId
        in: path
        description: Intelycare's Unique identifier of the shift.
        example: '10174202'
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - externalShiftId
              - shiftStartTime
              - shiftEndTime
              - shiftUnit
              - healthcareProfessionalType
              - shiftSource
              properties:
                shiftStartTime:
                  description: Shift start date/time can be in the UTC timezone in ISO 8601 format ex. "2024-01-24T05:04:34Z" OR Local Time by omitting the "Z" at the end. ex. "2024-01-24T05:04:34". The local time will be based on the configuration of the facility in the IntelyCare system.
                  type: string
                  example: 'UTC: 2024-01-24T05:04:34Z, local time: 2024-01-24T05:04:34'
                shiftEndTime:
                  description: Shift end date/time can be in the UTC timezone in ISO 8601 format ex. "2024-01-24T05:04:34Z" OR Local Time by omitting the "Z" at the end. ex. "2024-01-24T05:04:34". The local time will be based on the configuration of the facility in the IntelyCare system.
                  type: string
                  example: 'UTC: 2024-01-24T05:04:34Z, local time: 2024-01-24T05:04:34'
                shiftUnit:
                  description: Facility unit where the care should be delivered by the healthcare professional
                  type: string
                healthcareProfessionalType:
                  description: 'Healthcare professional qualification needed for the given shift. For example: “CNA”,”LPN”,”RN”.'
                  type: string
                shiftSource:
                  description: Shift origination point
                  type: string
                shiftBoostPercentage:
                  description: Percentage amount for boosting the shift
                  type: integer
                  default: 0
                timezone:
                  description: Timezone for the shifts
                  type: string
            example:
              shiftStartTime: '2024-01-16T23:00:00'
              shiftEndTime: '2024-01-17T07:00:00'
              shiftUnit: 1st Floor
              healthcareProfessionalType: LPN
              shiftSource: qwerty
              shiftBoostPercentage: 10
              timezone: ET
            x-codeSamples:
            - lang: cURL
              label: CLI
              source: 'curl --request POST \

                --url ''https://data.apiexample.com/api/example/batch_query/json?format=json'' \

                --header ''content-type: application/octet-stream: '' \

                --data ''{}''

                '
      responses:
        '200':
          description: 200 OK
          content:
            application/json:
              example:
                data:
                  clientId: 1234
                  internalShiftId: 10174202
                  externalShiftId: '2546810'
                  shiftStartTime: '2024-01-16T23:00:00'
                  shiftEndTime: '2024-01-17T07:00:00'
                  shiftDate: '2024-01-16'
                  shiftUnit: 1st Floor
                  healthcareProfessionalType: LPN
                  shiftSource: qwerty
                  shiftBoostPercentage: 10
                  timezone: ET
        '400':
          description: 400 Bad Request
          headers:
            IC-CorrelationID:
              $ref: '#/components/schemas/IC-CorrelationID'
          content:
            application/json:
              examples:
                foo:
                  value:
                    message: Shift ID is not valid!
        '401':
          $ref: '#/components/responses/UnauthorizedError'
    delete:
      tags:
      - Shift
      operationId: shift_delete_api_v1
      summary: Delete
      security:
      - ApiKeyAuth: []
      parameters:
      - name: X-API-KEY
        in: header
        description: API key issued to a specific client. This can only be used to access data within the client scope.
        example: d1015a83-9f5f-4a4d-b5fd-4e756ed1d282
        required: true
        schema:
          type: string
      - name: X-CLIENT-ID
        in: header
        description: Intelycare's Unique identifier of the client.
        example: '1234'
        required: true
        schema:
          type: string
      - name: shiftId
        in: path
        description: Intelycare's Unique identifier of the shift.
        example: '10174202'
        required: true
        schema:
          type: string
      responses:
        '200':
          description: 200 OK
          content:
            application/json:
              example:
                data:
                  internalShiftId: 10174202
                  shiftDate: '2024-01-16'
                  removed: 1
        '400':
          description: 400 Bad Request
          headers:
            IC-CorrelationID:
              $ref: '#/components/schemas/IC-CorrelationID'
          content:
            application/json:
              examples:
                foo:
                  value:
                    message: Shift ID is not valid!
        '401':
          $ref: '#/components/responses/UnauthorizedError'
components:
  responses:
    UnauthorizedError:
      description: Unauthorized
      headers:
        WWW_Authenticate:
          schema:
            type: string
      content:
        application/json:
          examples:
            foo:
              value:
                message: Unauthorized
  schemas:
    IC-CorrelationID:
      description: Unique uuid that can be used for debugging purposes
      type: string
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
    HMACSignature:
      type: apiKey
      in: header
      name: X-Signature-IC
x-tagGroups:
- name: APIs
  tags:
  - Shift
  - Timecard
  - Webhook Events
  - Check In / Check Out
